name: mcp_toolkit
description: A tool that utilizes annotation and extracts metadata from models for mcp tools
version: 0.1.0
homepage: https://github.com/JasperEssien2/mcp_toolkit
repository: https://github.com/JasperEssien2/mcp_toolkit

environment:
  sdk: ">=3.9.2 <4.0.0"

# Add regular dependencies here.
dependencies:
  collection: ^1.19.1
  equatable: ^2.0.7

dev_dependencies:
  lints: ^6.0.0
  pyramid_lint: ^2.3.0
  test: ^1.26.3
